#!/usr/bin/env bash

ban () {
  if [ "$localized" = "yes" ]; then
    echo "Not banning private IP space..."
    exit 0
  fi

  if [ "$offender" = "$(dig $1  | grep -A1 "ANSWER SECTION" | awk '{print $5}' | tail -n1)" ]; then
    echo "Not banning $1..."
    exit 0
  else
    # set the firwall, we'll try ipv4 first, if there is an error, then we'll try ipv6
    firewall-cmd --permanent --add-rich-rule="rule family='ipv4' source address='$offender' reject" || firewall-cmd --permanent --add-rich-rule="rule family='ipv6' source address='$offender' reject" 
    # bring this one in if there is ever a bug with RFC 4038 implementation
    # tested on 8/24/20 CentOS 7 and this next commented one is commented because it 
    # is currently not needed because the padded IPv4 address gets properly processed through the IPv4 rules.
    # firewall-cmd --permanent --add-rich-rule="rule family='ipv6' source address='::ffff:$offender' reject"
    firewall-cmd --reload
  fi
}

export offender=$(while read line; do echo $line | awk '{ print $16}' | cut -d'=' -f2; done<&0)
export localized=yes
echo $offender | grep 10. || localized=no

export dnsreverse=$(dig $offender | grep -A1 ANSWER | tail -n1 | awk '{ print $5 }')

if [ -z "$dnsreverse" ]; then
   ban $1 # the first argument is a DNS name to NOT ban
else
   export offender=$dnsreverse
   ban $1 # the first argument is a DNS name to NOT ban
fi
